"""Sentences not to be considered in any analysis
"""

excluded_sentences = [
'You may be able to find the same content in another format, or you may be able to find more information, at their web site.',
'Invalid email Something went wrong, please try again later.',
'If you are using ad-blocking software, please disable it and reload the page.',
'You can unsubscribe at any time.',
'This may include adverts from us and 3rd parties based on our understanding.',
'This content is imported from Instagram.',
'Related Gallery.',
'Loading Something is loading.',
'0 votes so far.',
'Something went wrong, please try again later.',
'Over 3 million people read Morning Brew ; you should too!',
'Gift Outline Gift Article.',
'This content is imported from You Tube.',
'This content is imported from Twitter.',
'Source (1).',
'Read our privacy notice Thanks for signing up to the Football email {{ #verify Errors }}{{ message }}{{ /verify Errors }}{{ ^verify Errors }}Something went wrong.',
"Visit Insider's homepage for more stories.",
'Wp Get the full experience.',
'Contact us at .',
'G/O Media may get a commission 38% Off Echo Show 8 Alexa?Has an 8" HD touchscreen which can let you watch shows, stream things, or even make video calls thanks to the 13 MP camera, you can also use it to control other smart devices in your home with ease, and even display photos if you want to as a digital photo frame.',
'You can unsubscribe at any time by clicking the unsubscribe link at the bottom of the newsletter email.',
'This is a carousel.',
'Be sure to like Matt & Jess on Facebook for more updates!.',
'This video is unavailable because we were unable to load a message from our sponsors.',
'Sign up for our Email Newsletters here..',
'Read our privacy notice Thanks for signing up to the Breaking News email {{ #verify Errors }}{{ message }}{{ /verify Errors }}{{ ^verify Errors }}Something went wrong.',
'Content This content can also be viewed on the site it originates from.',
'This content is imported from {embed-name}.',
'Read our privacy notice Thanks for signing up to the The Life Cinematic email {{ #verify Errors }}{{ message }}{{ /verify Errors }}{{ ^verify Errors }}Something went wrong.',
'Click here for more details LIVE POLL Q.',
'Instagram content This content can also be viewed on the site it originates from.',
'Please try again later.',
'Please review their details and accept them to load the content.',
'email digishowbiz@the- or call us direct on 02077824220.',
'SHARE THIS ARTICLE ON.',
'"This content is imported from Instagram.',
'Get a daily selection of our top stories based on your reading preferences.',
'Sorry, there seem to be some issues.',
'Like this article?',
"We use your sign-up to provide content in ways you've consented to and to improve our understanding of you.",
'We pay for videos too.',
'Read our privacy notice Thanks for signing up to the Indy Arts email {{ #verify Errors }}{{ message }}{{ /verify Errors }}{{ ^verify Errors }}Something went wrong.',
'Follow @htshowbiz for more.',
'ADVERTISEMENT.',
'All rights reserved.',
"G/O Media may get a commission $10 or more Humble Bundle - Starlight Bundle Benefit the Starlight Children's Foundation For $10 or more, you can help hospitalized kids get access to video gamesand get some sweet games for yourself too, including Lego Star Wars - The Complete Saga.",
'Sign up for our Email Newsletters here.',
'Let us know in the comments below!.',
"Interested in Digital Spy's weekly newsletter?",
"Visit Business Insider's homepage for more stories.",
'The video will auto-play soon 8 Cancel We have more newsletters Something went wrong, please try again later.',
'Get HBO, Starz, Showtime and MORE for FREE with a no-risk, 7-day free trial of Amazon Channels.',
"A former WWE writer rates Triple H's regime a C-.",
'Listen to Behind the Lines podcast.',
'Read More.',
'Further reading.',
'We have more newsletters Something went wrong, please try again later.',
'You will receive a verification email shortly.',
'Please refresh the page and try again.',
'By submitting your information you agree to the Terms & Conditions (opens in new tab) and Privacy Policy (opens in new tab) and are aged 16 or over.',
'Related.',
'Sign up to our newsletter to get more articles like this delivered straight to your inbox.',
'[email protected].',
'"Visit Insider\'s homepage for more stories.',
'(Photo by Kelly A.',
'By submitting your email, you agree to our Terms and Privacy Policy and to receive email correspondence from us.',
'Twitter content This content can also be viewed on the site it originates from.',
'READ NEXT:.',
'"Never miss a story  sign up for PEOPLE\'s free daily newsletter to stay up-to-date on the best of what PEOPLE has to offer, from juicy celebrity news to compelling human interest stories.',
'Android & IOS users, download our mobile app for faster than ever Bollywood & Box Office updates!.',
'Follow Artnet News on Facebook:.',
'Related content:.',
'Once you have subscribed we will use the email you provided to send you the newsletter.',
'Read our privacy notice Thanks for signing up to the Roisin OConnors email {{ #verify Errors }}{{ message }}{{ /verify Errors }}{{ ^verify Errors }}Something went wrong.',
'Let us know in the comments!.',
'We need your consent to load this Social Media content We use a number of different Social Media outlets to manage extra content that can set cookies on your device and collect data about your activity.',
'Like this story?',
'Let us know in the comments below.',
'How do you sign up?',
"And that's it, you're all set.",
'Have something to add to this story?',
"Just hit 'Like' on our Digital Spy Facebook page and 'Follow' on our @digitalspy Twitter account and you're all set..",
'All rights reserved..',
'Digital Spy now has a newsletter  sign up to get it sent straight to your inbox.',
'Source (1) (2).',
'Photo by Getty Images.',
'Let us know below, or by hitting us up on Facebook and Twitter!.',
'SIGN UP.',
'Twitter | Facebook | Instagram | You Tube',
'Iloura/Warner Bros. Ent.',
]